#!/bin/sh
# Pass in sleep (seconds) as $1

sleep $1

EMERGE_PID=`ps -A | grep emerge | awk '{print $1}'`
cgroup=$(mktemp -d --tmpdir=/sys/fs/cgroup/cpu portage-XXXX) &&
echo $EMERGE_PID > "${cgroup}/tasks" &&
echo 1 > "${cgroup}/notify_on_release" &&
echo 256 > "${cgroup}/cpu.shares"
